/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as AuthenticatedPortalDashboardRouteImport } from './routes/_authenticated/portal.dashboard'
import { Route as GroupsSlugIndexRouteImport } from './routes/groups.$slug.index'
import { Route as GroupsSlugActivityPostRouteImport } from './routes/groups.$slug.$activity.$post'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalDashboardRoute =
  AuthenticatedPortalDashboardRouteImport.update({
    id: '/portal/dashboard',
    path: '/portal/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const GroupsSlugIndexRoute = GroupsSlugIndexRouteImport.update({
  id: '/groups/$slug/',
  path: '/groups/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugActivityPostRoute = GroupsSlugActivityPostRouteImport.update({
  id: '/groups/$slug/$activity/$post',
  path: '/groups/$slug/$activity/$post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/memories': typeof MemoriesRoute
  '/portal/login': typeof PortalLoginRoute
  '/groups/': typeof GroupsIndexRoute
  '/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/groups/$slug/': typeof GroupsSlugIndexRoute
  '/groups/$slug/$activity/$post': typeof GroupsSlugActivityPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/memories': typeof MemoriesRoute
  '/portal/login': typeof PortalLoginRoute
  '/groups': typeof GroupsIndexRoute
  '/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/groups/$slug': typeof GroupsSlugIndexRoute
  '/groups/$slug/$activity/$post': typeof GroupsSlugActivityPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/memories': typeof MemoriesRoute
  '/portal/login': typeof PortalLoginRoute
  '/groups/': typeof GroupsIndexRoute
  '/_authenticated/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/groups/$slug/': typeof GroupsSlugIndexRoute
  '/groups/$slug/$activity/$post': typeof GroupsSlugActivityPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/memories'
    | '/portal/login'
    | '/groups/'
    | '/portal/dashboard'
    | '/groups/$slug/'
    | '/groups/$slug/$activity/$post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/memories'
    | '/portal/login'
    | '/groups'
    | '/portal/dashboard'
    | '/groups/$slug'
    | '/groups/$slug/$activity/$post'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/memories'
    | '/portal/login'
    | '/groups/'
    | '/_authenticated/portal/dashboard'
    | '/groups/$slug/'
    | '/groups/$slug/$activity/$post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  MemoriesRoute: typeof MemoriesRoute
  PortalLoginRoute: typeof PortalLoginRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsSlugIndexRoute: typeof GroupsSlugIndexRoute
  GroupsSlugActivityPostRoute: typeof GroupsSlugActivityPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/dashboard': {
      id: '/_authenticated/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof AuthenticatedPortalDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/groups/$slug/': {
      id: '/groups/$slug/'
      path: '/groups/$slug'
      fullPath: '/groups/$slug/'
      preLoaderRoute: typeof GroupsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug/$activity/$post': {
      id: '/groups/$slug/$activity/$post'
      path: '/groups/$slug/$activity/$post'
      fullPath: '/groups/$slug/$activity/$post'
      preLoaderRoute: typeof GroupsSlugActivityPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalDashboardRoute: typeof AuthenticatedPortalDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalDashboardRoute: AuthenticatedPortalDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  MemoriesRoute: MemoriesRoute,
  PortalLoginRoute: PortalLoginRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsSlugIndexRoute: GroupsSlugIndexRoute,
  GroupsSlugActivityPostRoute: GroupsSlugActivityPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
